extensions:
    pim-product-index:
        module: pim/common/simple-view
        targetZone: self
        config:
            template: pim/template/common/default-template
        forwarded-events:
            grid_load:start: grid_load:start
            grid_load:complete: grid_load:complete

    pim-product-index-grid-container:
        module: pim/product/grid/container
        parent: pim-product-index
        targetZone: content

    pim-product-index-create-button:
        module: pim/form/common/product/create-button
        parent: pim-product-index
        targetZone: buttons
        config:
            buttonTitle: pim_enrich.entity.product.create
            modalTitle: pim_enrich.entity.product.modalTitle
            subTitle: pim_enrich.entity.product.subTitle
            choices:
                create-product:
                    form: pim-product-create-modal
                    title: pim_enrich.entity.product.create_popin.type
                    icon: icon-product
                    aclResourceId: pim_enrich_product_create
                create-product-model:
                    form: pim-product-model-create-modal
                    title: pim_enrich.entity.product_model.create_popin.type
                    icon: icon-model
                    aclResourceId: pim_enrich_product_model_create

    pim-product-index-locale-switcher:
        module: pim/grid/locale-switcher
        parent: pim-product-index-column-inner
        targetZone: column-context-switcher
        position: 10
        config:
            routeName: pim_enrich_product_index
            localeParamName: dataLocale

    pim-product-index-view-selector:
        module: pim/grid/view-selector
        parent: pim-product-index-column-inner
        targetZone: view-selector
        config:
            gridName: product-grid

